### ISSUE TITLE
Regararding LPF value for smoothing

### ISSUE THREAD

**Issue by MohSamNaf** [MVRonkin/dsatools#5]
Thank you for your work on HVD.

I am having a question regarding the Low Pass Filtering value which acts as a smoothing factor for HVD decomposition. In one of the references you mentioned, the LPF value is usually very low around 0.02 to 0.05Hz. However, I see your implementation here is different with values up to 20 and 30. What does these values mean?

**Comment by MVRonkin** [comment]
Hello, thanks for using my library. If I understand you correctly, the cut-off frequency depends on the components you want to extract. In my case, the frequency set in points, instead of Hz.
